CREATE DATABASE %%PROJECT_NAME;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE USER %%PROJECT_NAME;
ALTER USER %%PROJECT_NAME WITH ENCRYPTED PASSWORD '%%PROJECT_PASSWORD';
ALTER USER %%PROJECT_NAME WITH SUPERUSER;
